version: '3.8'

services:
  divvy_app:
    build: .
    container_name: divvy_app
    ports:
      - "8501:8501"   # Map Streamlit default port 8501
    volumes:
      - .:/app        # Mount the current directory to the container
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped   # Automatically restart the container if it fails
